version: '3'
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        logging:
           driver: none 
    
    webhook:
        build: './webhook'
        ports:
            - "4000:4000"
        depends_on: 
            - db
        env_file: 
            - ./webhook/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
            
    auth:
        build: './auth'
        ports:
            - "4001:4000"
        depends_on: 
            - db
        env_file: 
            - ./auth/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
    
    search:
        build: './search'
        ports:
            - "4002:4000"
        depends_on: 
            - db
        env_file: 
            - ./search/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices

        