version: '3'
services:

    db:
        image: mongo
        ports:
            - "27017:27017"
        logging: 
            driver: none
        
    
    webhook:
        build: './webhook'
        volumes:
            - "./test"
        ports:
            - "4000:4000"
        depends_on: 
            - db
            - gateway
        env_file: 
            - ./webhook/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
            
    auth:
        build: './auth'
        ports:
            - "4001:4000"
        depends_on: 
            - db
            - gateway
        env_file: 
            - ./auth/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
    
    cars:
        build: './cars'
        ports:
            - "4002:4000"
        depends_on: 
            - db
            - gateway
        env_file: 
            - ./cars/.env
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
            
    orders:
        build: './orders'
        ports:
            - "4004:4000"
        depends_on: 
            - db
            - gateway
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
    
    message:
        build: './message'
        ports:
            - "4005:4000"
        depends_on: 
            - db
            - gateway
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
    
    search:
        build: './search'
        ports:
            - "4006:4000"
        depends_on: 
            - db
            - gateway
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices

    tracking:
        build: './tracking'
        ports:
            - "4007:4000"
        depends_on: 
            - db
            - gateway
        environment: 
            - MONGO_DB_URI=mongoDB://db/microservices
        
    gateway:
        build: './gateway'
        ports:
            - "8080:8080"
        environment: 
            - LOG_LEVEL=debug

        