https:
  port: 8080
  tls:
    "default":
      key: "./config/certificates/tls.key"
      cert: "./config/certificates/tls.crt"
      ca: ["./config/certificates/chain.pem"]
apiEndpoints:
  auth:
    paths: 
      - '/auth/*'
  cars:
    paths:
      - '/cars/*'
      - '/make/*'
      - '/model/*'
      - '/fuel/*'
      - '/class/*'
      - '/review/*'
  webhook:
    paths:
      - '/webhook/*'
  orders:
    paths:
      - '/orders/*'
  search:
    paths:
      - '/search/*'
  message:
    paths:
      - '/message/*'
serviceEndpoints:
  auth:
    url: 'http://auth:4000'
  cars:
    url: 'http://cars:4000'
  webhook:
    url: 'http://webhook:4000'
  orders:
    url: 'http://orders:4000'
  search:
    url: 'http://search:4000'
  message:
    url: 'http://message:4000'

policies:
  - proxy
  - rate-limit
  - cors
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - rate-limit: &rate-limit
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: &proxy
            serviceEndpoint: auth
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
  cars:
    apiEndpoints:
      - cars
      - make
      - model
      - fuel
      - class
      - review
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: cars
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
  message:
    apiEndpoints:
      - message
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: message
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
  webhook:
    apiEndpoints:
      - webhook
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: webhook
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
  orders:
    apiEndpoints:
      - orders
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: orders
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
  search:
    apiEndpoints:
      - search
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: search
            changeOrigin: true
      - cors:
        - action:
            origin: ['http://localhost:3000', 'http://localhost:3001', 'https://localhost:8080']
            methods: 'HEAD,PUT,PATCH,POST,DELETE'
