https:
  port: 8080
  tls:
    "default":
      key: "./config/certificates/tls.key"
      cert: "./config/certificates/tls.crt"
      ca: ["./config/certificates/chain.pem"]
apiEndpoints:
  auth:
    paths: 
      - '/auth/*'
  cars:
    paths:
      - '/cars/*'
      - '/make/*'
      - '/model/*'
      - '/fuel/*'
      - '/class/*'
  webhook:
    paths:
      - '/webhook/*'
  orders:
    paths:
      - '/orders/*'
  search:
    paths:
      - '/search/*'
serviceEndpoints:
  auth:
    url: 'http://auth:4000'
  cars:
    url: 'http://cars:4000'
  webhook:
    url: 'http://webhook:4000'
  orders:
    url: 'http://orders:4000'
  search:
    url: 'http://search:4000'
policies:
  - proxy
  - rate-limit
  - cors
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - rate-limit: &rate-limit
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: &proxy
            serviceEndpoint: auth
            changeOrigin: true
  cars:
    apiEndpoints:
      - cars
      - make
      - model
      - fuel
      - class
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: cars
            changeOrigin: true
  webhook:
    apiEndpoints:
      - webhook
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: webhook
            changeOrigin: true
  orders:
    apiEndpoints:
      - orders
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: orders
            changeOrigin: true
  search:
    apiEndpoints:
      - search
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: search
            changeOrigin: true
