https:
  port: 8080
  tls:
    "default":
      key: "./config/certificates/root.key"
      cert: "./config/certificates/root.crt"
  options:
    "rejectUnauthorized": true
apiEndpoints:
  auth:
    paths: 
      - '/auth/*'
  cars:
    paths:
      - '/cars/*'
  webhook:
    paths:
      - '/webhook/*'
serviceEndpoints:
  auth:
    url: 'http://auth:4000'
  cars:
    url: 'http://cars:4000'
  webhook:
    url: 'http://webhook:4000'
policies:
  - proxy
  - rate-limit
  - cors
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - rate-limit: &rate-limit
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: &proxy
            serviceEndpoint: auth
            changeOrigin: true
  cars:
    apiEndpoints:
      - cars
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: cars
            changeOrigin: true
  webhook:
    apiEndpoints:
      - webhook
    policies:
      - rate-limit:
        - action:
            max: 10
            windowMs: 1000
      - proxy:
        - action: 
            serviceEndpoint: webhook
            changeOrigin: true
